package com.pillyliu.pinprofandroid.gameroom

import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import kotlinx.coroutines.CoroutineScope

@Composable
internal fun GameRoomScreenSettingsRouteHost(
    store: GameRoomStore,
    catalogLoader: GameRoomCatalogLoader,
    pinsideImportService: GameRoomPinsideImportService,
    scope: CoroutineScope,
    selectedSettingsSection: GameRoomSettingsSection,
    onSelectedSettingsSectionChange: (GameRoomSettingsSection) -> Unit,
    onBack: () -> Unit,
    settingsSaveFeedbackMessage: String?,
    settingsSaveFeedbackTick: Int,
    importSourceInput: String,
    onImportSourceInputChange: (String) -> Unit,
    importSourceURL: String,
    onImportSourceURLChange: (String) -> Unit,
    importIsLoading: Boolean,
    onImportIsLoadingChange: (Boolean) -> Unit,
    importErrorMessage: String?,
    onImportErrorMessageChange: (String?) -> Unit,
    importResultMessage: String?,
    onImportResultMessageChange: (String?) -> Unit,
    importRows: List<ImportDraftRow>,
    onImportRowsChange: (List<ImportDraftRow>) -> Unit,
    importReviewFilter: ImportReviewFilter,
    onImportReviewFilterChange: (ImportReviewFilter) -> Unit,
    nameExpanded: Boolean,
    onNameExpandedChange: (Boolean) -> Unit,
    venueNameDraft: String,
    onVenueNameDraftChange: (String) -> Unit,
    onSettingsSaveFeedback: (String) -> Unit,
    addMachineExpanded: Boolean,
    onAddMachineExpandedChange: (Boolean) -> Unit,
    areasExpanded: Boolean,
    onAreasExpandedChange: (Boolean) -> Unit,
    areaNameDraft: String,
    onAreaNameDraftChange: (String) -> Unit,
    areaOrderDraft: String,
    onAreaOrderDraftChange: (String) -> Unit,
    selectedAreaID: String?,
    onSelectedAreaIDChange: (String?) -> Unit,
    editMachinesExpanded: Boolean,
    onEditMachinesExpandedChange: (Boolean) -> Unit,
    allMachines: List<OwnedMachine>,
    selectedEditMachine: OwnedMachine?,
    onSelectedEditMachineChange: (String?) -> Unit,
    draftVariant: String,
    onDraftVariantChange: (String) -> Unit,
    draftAreaID: String?,
    onDraftAreaIDChange: (String?) -> Unit,
    draftStatus: String,
    onDraftStatusChange: (String) -> Unit,
    draftGroup: String,
    onDraftGroupChange: (String) -> Unit,
    draftPosition: String,
    onDraftPositionChange: (String) -> Unit,
    draftPurchaseSource: String,
    onDraftPurchaseSourceChange: (String) -> Unit,
    draftSerialNumber: String,
    onDraftSerialNumberChange: (String) -> Unit,
    draftOwnershipNotes: String,
    onDraftOwnershipNotesChange: (String) -> Unit,
    archiveFilter: GameRoomArchiveFilter,
    onArchiveFilterChange: (GameRoomArchiveFilter) -> Unit,
    onOpenArchivedMachineView: (String) -> Unit,
) {
    GameRoomSettingsRoute(
        selectedSettingsSection = selectedSettingsSection,
        onSelectedSettingsSectionChange = onSelectedSettingsSectionChange,
        onBack = onBack,
        errorMessage = store.lastErrorMessage,
        overlayContent = {
            GameRoomFloatingSaveFeedbackOverlay(
                message = settingsSaveFeedbackMessage,
                token = settingsSaveFeedbackTick,
                modifier = Modifier.align(Alignment.Center),
            )
        },
        importContent = {
            GameRoomScreenImportSettingsRouteContent(
                store = store,
                catalogLoader = catalogLoader,
                pinsideImportService = pinsideImportService,
                scope = scope,
                importSourceInput = importSourceInput,
                onImportSourceInputChange = onImportSourceInputChange,
                importSourceURL = importSourceURL,
                onImportSourceURLChange = onImportSourceURLChange,
                importIsLoading = importIsLoading,
                onImportIsLoadingChange = onImportIsLoadingChange,
                importErrorMessage = importErrorMessage,
                onImportErrorMessageChange = onImportErrorMessageChange,
                importResultMessage = importResultMessage,
                onImportResultMessageChange = onImportResultMessageChange,
                importRows = importRows,
                onImportRowsChange = onImportRowsChange,
                importReviewFilter = importReviewFilter,
                onImportReviewFilterChange = onImportReviewFilterChange,
            )
        },
        editContent = {
            GameRoomScreenEditSettingsRouteContent(
                store = store,
                catalogLoader = catalogLoader,
                nameExpanded = nameExpanded,
                onNameExpandedChange = onNameExpandedChange,
                venueNameDraft = venueNameDraft,
                onVenueNameDraftChange = onVenueNameDraftChange,
                onSettingsSaveFeedback = onSettingsSaveFeedback,
                addMachineExpanded = addMachineExpanded,
                onAddMachineExpandedChange = onAddMachineExpandedChange,
                areasExpanded = areasExpanded,
                onAreasExpandedChange = onAreasExpandedChange,
                areaNameDraft = areaNameDraft,
                onAreaNameDraftChange = onAreaNameDraftChange,
                areaOrderDraft = areaOrderDraft,
                onAreaOrderDraftChange = onAreaOrderDraftChange,
                selectedAreaID = selectedAreaID,
                onSelectedAreaIDChange = onSelectedAreaIDChange,
                editMachinesExpanded = editMachinesExpanded,
                onEditMachinesExpandedChange = onEditMachinesExpandedChange,
                allMachines = allMachines,
                selectedEditMachine = selectedEditMachine,
                onSelectedEditMachineChange = onSelectedEditMachineChange,
                draftVariant = draftVariant,
                onDraftVariantChange = onDraftVariantChange,
                draftAreaID = draftAreaID,
                onDraftAreaIDChange = onDraftAreaIDChange,
                draftStatus = draftStatus,
                onDraftStatusChange = onDraftStatusChange,
                draftGroup = draftGroup,
                onDraftGroupChange = onDraftGroupChange,
                draftPosition = draftPosition,
                onDraftPositionChange = onDraftPositionChange,
                draftPurchaseSource = draftPurchaseSource,
                onDraftPurchaseSourceChange = onDraftPurchaseSourceChange,
                draftSerialNumber = draftSerialNumber,
                onDraftSerialNumberChange = onDraftSerialNumberChange,
                draftOwnershipNotes = draftOwnershipNotes,
                onDraftOwnershipNotesChange = onDraftOwnershipNotesChange,
            )
        },
        archiveContent = {
            GameRoomArchiveSettingsSection(
                store = store,
                archiveFilter = archiveFilter,
                onArchiveFilterChange = onArchiveFilterChange,
                onOpenMachineView = onOpenArchivedMachineView,
            )
        },
    )
}
